version: '3.8'

services:
  book-api:
    build: .
    container_name: book-api
    image: app:latest
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./books.db:/app/books.db